name: Update version

on:
  pull_request:
    types:
      - closed
    branches:
      - master
      - main

jobs:
  create-new-tag:
    if: ${{ github.event.pull_request.merged }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create new tag
        run: ./gradlew :auto-api-java:release -Prelease.useAutomaticVersion=true
